insert into curated_zone.trips_fact (
tripduration ,
starttime ,
stoptime ,
start_station_id ,
start_station_latitude ,
start_station_longitude ,
end_station_id ,
end_station_latitude ,
end_station_longitude ,
bikeid ,
membership_type ,
usertype ,
birth_year ,
gender)
select tripduration ,
starttime ,
stoptime ,
start_station_id ,
start_station_latitude ,
start_station_longitude ,
end_station_id ,
end_station_latitude ,
end_station_longitude ,
bikeid ,
membership_type ,
usertype ,
birth_year ,
gender
from LANDING_ZONE.TRIPS;